#!/usr/bin/env python

import wai

from argparse import ArgumentParser

p = ArgumentParser(description="Checks whether a hostname leads to this host")

p.add_argument("hostname", action="store", help="The hostname to check")
p.add_argument("-v", "--verbose", action="store_true", default=False, help="Be verbose")

opts = p.parse_args()

if wai.check(opts.hostname):
    if opts.verbose:
        print "OK:%s points to this host" % opts.hostname
    exit(0)
else:
    if opts.verbose:
        print "ERROR:%s points to another host" % opts.hostname
    exit(1)
